# Generated by Django 4.2.4 on 2023-08-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0003_alter_bet_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='footballand.footballteam'),
        ),
    ]
