# Generated by Django 4.2.4 on 2023-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0005_match_active_match_result_team_1_match_result_team_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2',
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ManyToManyField(related_name='team_1', to='footballand.footballteam'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ManyToManyField(related_name='team_2', to='footballand.footballteam'),
        ),
    ]
