# Generated by Django 4.2.4 on 2023-08-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0006_remove_match_team_1_remove_match_team_2_match_team_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2',
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='footballand.footballteam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='footballand.footballteam'),
            preserve_default=False,
        ),
    ]
