# Generated by Django 4.2.4 on 2023-08-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0007_remove_match_team_1_remove_match_team_2_match_team_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
