# Generated by Django 4.2.4 on 2023-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0010_alter_match_result_team_1_alter_match_result_team_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
