# Generated by Django 4.2.4 on 2023-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0011_bet_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
