# Generated by Django 4.2.4 on 2023-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0012_bet_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='daily_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
