# Generated by Django 4.2.4 on 2023-08-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0013_player_daily_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='previous_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
