# Generated by Django 3.2.20 on 2023-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0015_rename_previous_login_date_player_previous_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='draw_ratio',
            new_name='profit_ratio_draw',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='win_ratio_team_1',
            new_name='profit_ratio_team_1_win',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='win_ratio_team_2',
            new_name='profit_ratio_team_2_win',
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(default='La Liga', max_length=500),
        ),
    ]
