# Generated by Django 3.2.20 on 2023-08-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballand', '0018_alter_match_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballteam',
            name='league',
        ),
        migrations.RemoveField(
            model_name='footballteam',
            name='table_position',
        ),
        migrations.RemoveField(
            model_name='league',
            name='country',
        ),
    ]
